# welcome to numpy#


In [1]:
import numpy as np

In [2]:
myarr= np.array([[1,2,3,7]],np.int8)

In [3]:
myarr

array([[1, 2, 3, 7]], dtype=int8)

In [4]:
myarr[(0,1)]

2

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int8')

In [7]:
myarr[0,1]=45

In [8]:
myarr

array([[ 1, 45,  3,  7]], dtype=int8)

# Array creation : conversion from python structure

In [9]:
listarray=np.array([[1,2,3],[5,6,7],[8,9,10]])

In [10]:
listarray

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

In [14]:
array=np.zeros((3,3))

In [15]:
array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
array.dtype

dtype('float64')

In [17]:
array.shape

(3, 3)

In [18]:
array.size

9

In [19]:
array1=np.ones((2,3))

In [20]:
array1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
array1.dtype

dtype('float64')

In [22]:
array1.shape

(2, 3)

In [23]:
array1.size

6

In [24]:
range=np.arange(14),np.float64

In [25]:
range

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]),
 numpy.float64)

In [26]:
lshape=np.linspace(1,10,5)

In [27]:
lshape

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [28]:
emp=np.empty((4,6))

In [29]:
emp

array([[6.23042070e-307, 3.56043053e-307, 1.60219306e-306,
        7.56571288e-307, 1.89146896e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 1.33511018e-306, 6.23057689e-307,
        7.56602524e-307, 8.45559303e-307, 8.06612616e-308],
       [6.89810244e-307, 1.22387550e-307, 2.22522596e-306,
        8.34423917e-308, 1.11261162e-306, 1.78021527e-306]])

In [30]:
emp_like=np.empty_like(lshape)

In [31]:
emp_like

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [32]:
ide=np.identity(3)

In [33]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
ide.shape

(3, 3)

In [35]:
ide.size

9

In [36]:
ide.dtype

dtype('float64')

In [37]:
array2=np.arange(10)

In [38]:
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
array2.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
array2.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
array2.shape

(10,)

# Axis Calculation by Numpy

In [42]:
x=([1,2,3]),([4,5,6]),([7,8,9])

In [43]:
arr=np.array(x)

In [44]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr.sum(axis=0)

array([12, 15, 18])

In [46]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [47]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [48]:
arr.flat

In [49]:
x=np.zeros((8,8))

In [53]:
x[1::2,::2]=1

In [54]:
x[::2,1::2]=1

In [55]:
x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])